slick {
  driver = "slick.jdbc.H2Profile$"
  version_control_dir = "./.db"
  db {
    url = "jdbc:h2:./test.tb"
    driver = "org.h2.Driver"
    connectionPool = "HikariCP"
    connectionTimeout = 5000
    maximumPoolSize = 10
  }
}
